
   - name: Stop service firewalld, if started
     service:
       name: firewalld
       state: stopped
       enabled: no

   - name: disable selinux
     selinux:
       state: disabled

   - name: Selinux disable permanently 
     replace:
       path: /etc/selinux/config
       regexp: '(\s+)SELINUX=enabled'
       replace: '\1SELINUX=disabled\2'
       backup: yes
  
   - name: download alertmanager.tar.gz
     shell: wget https://github.com/prometheus/alertmanager/releases/download/v0.15.2/alertmanager-0.15.2.linux-amd64.tar.gz

   - name: configure alertmanager
     shell: |
       tar xvf alertmanager-0.15.2.linux-amd64.tar.gz -C /usr/local/
       touch /etc/systemd/system/alertmanager.service


   - name: create and configure the alertmanager.yml 
     blockinfile:
       path: /etc/systemd/system/alertmanager.service
       block: |
        [Unit]
        Description=Alertmanager
        After=network-online.target
 
        [Service]
        Restart=on-failure
        ExecStart=/usr/local/alertmanager-0.15.2.linux-amd64/alertmanager --config.file=/usr/local/alertmanager-0.15.2.linux-amd64/alertmanager.yml
 
        [Install]
        WantedBy=multi-user.target
 


   - name: Start alertmanager service
     service:
       name: alertmanager
       state: started
       enabled: yes

   - name: Ansible delete alertmanager.tar.gz
     file:
       path: /home/wasadm/alertmanager-0.15.2.linux-amd64.tar.gz
       state: absent
