global:
  resolve_timeout: 5m
  http_config: {}
  smtp_from: alertmanager@xxxxx
  smtp_hello: localhost
  smtp_smarthost: mail.xxxx.com:25
  smtp_require_tls: true
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  hipchat_api_url: https://api.hipchat.com/
  opsgenie_api_url: https://api.eu.opsgenie.com/
  opsgenie_api_key: xxxxxxxxxxxxxx
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
route:
  receiver: devopsteam
  routes:
  - receiver: warning
    match:
      severity: warning
  - receiver: critical
    match:
      severity: critical
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
receivers:
- name: default
- name: devopsteam
  email_configs:
  - send_resolved: true
    to: anil.dalkilic@xxxxx
    from: alertmanager@xxxx
    hello: localhost
    smarthost: mail.xxx.com:25
    headers:
      From: alertmanager@xxxxx
      Subject: Test environment alerts
      To: anil.dalkilic@xxxx.com
    html: '{{ template "email.default.html" . }}'
    require_tls: true
- name: warning
  opsgenie_configs:
  - send_resolved: true
    http_config: {}
    api_key: ------------------
    api_url: https://api.eu.opsgenie.com/
    message: '{{ template "opsgenie.default.message" . }}'
    description: '{{ template "opsgenie.default.description" . }}'
    source: '{{ template "opsgenie.default.source" . }}'
    tags: 'type:kafka'
    priority: P3
- name: critical
  opsgenie_configs:
  - send_resolved: true
    http_config: {}
    api_key: ---------------------
    api_url: https://api.eu.opsgenie.com/
    message: '{{ template "opsgenie.default.message" . }}'
    description: '{{ template "opsgenie.default.description" . }}'
    source: '{{ template "opsgenie.default.source" . }}'
    tags: 'type:kafka'
    priority: P1
templates: []
