        global:
          scrape_interval: 10s
        alerting:
          alertmanagers:
            - scheme: http
              api_version: v1              
              static_configs:
                - targets:
                    - "172.x.x.x:9093"
        rule_files:
          - "prometheus_rules.yml"
        scrape_configs:
          - job_name: 'prometheus_master'
            scrape_interval: 5s
            static_configs:
             - targets: ['localhost:9090']
          - job_name: redis_exporter_172_x_x_x
            scrape_interval: 5s
            static_configs:
             - targets: ['172.x.x.x:9121']
          - job_name: 'microservice_metrics'
            honor_labels: true
            metrics_path: '/metrics'
            scrape_interval: 15s
            static_configs:
              - targets: ['prometheus-pushgateway-xxxxx.apps.stdocker.xxx:80']
          - job_name: 'staging-kafka-xxxx'
            scrape_interval: 5s
            static_configs:
              - targets: ['xxxxxx:9308'] 
