        global:
          scrape_interval: 10s

        scrape_configs:
          - job_name: 'prometheus_master'
            scrape_interval: 5s
            static_configs:
             - targets: ['localhost:9090']
          - job_name: 'microservice_metrics'
            scrape_interval: 15s
            static_configs:
             - targets: ['prometheus-pushgateway-xxxxx.apps.prodocker.xxxxx:80','prometheus-pushgateway-xxxxxx.apps.prodocker.xxxx:80','prometheus-pushgateway-xxxxx.apps.prodocker.xxxx:80']
          - job_name: 'redis_prodserver1'
            scrape_interval: 10s
            static_configs:
             - targets: ['xxxxxx:9121']
